### ISSUE TITLE
Failed to get private key!

### ISSUE THREAD

**Issue by lukasheinz92** [schklom/Mirror-workflows#72]
When I enter the `user ID` and click on `Locate` then I get an error `Failed to get private key!`. I have tried to build my own image or use an existing image - https://hub.docker.com/r/schklom/findmydeviceserver but with the same result. I have also tried to use two different phones (one with Android and one with LineageOS).

I am running the `findmydeviceserver` on Raspberry Pi 4 using Docker Compose:

```
services:
  findmydeviceserver:
    image: schklom/findmydeviceserver:latest
    container_name: find_my_device
    ports:
      - 1020:1020/tcp
    volumes:
      - /path/to/appdata/find_my_device/:/go/src/fmd/objectbox
```
